name: Basic workflow
on: 
  workflow_dispatch:
    inputs:
      sample_input:
        description: 'Welcome to GitHub Actions'
        required: true
        type: string
        default: 'Hello, Github Action!'


jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/build-template.yml
    with:
      description: ${{ github.event.inputs.sample_input }}